### ISSUE TITLE
401 error loading with resourceKey provided

### ISSUE THREAD

**Issue by rolinger** [51Degrees/cloud-issues#1]
Hello,

I just setup two environments.  One as JS for client side detection and second for server side detection using php.

For the JS implementation, I am getting a 401 Authorization error on the initial script load:

```
    <script async src="https://cloud.51degrees.com/api/v4/myResourceKey.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            fod.complete(function (data) {
                console.log(data) ;
                // Fetch the properties from the JSON response and write to the page.
                addText("HardwareModel: " + data.device["hardwaremodel"]);
            });
        }

        addText = function(text) {
            console.log(text) ;
        }
    </script> 
```

In one sense I kind of get it, I defined a domain in the configurator:  *.mydomain.com - the JS client isn't originating from mydomain.com, but its where I am sending traffic to.

From the cloud configurator, it looks like everything is setup correctly.  But then in my PHP I am getting another Authentication error:

Uncaught Exception: Cloud request engine properties list request returned This resource key is not authorized for use with domain: ''. Please visit https://configure.51degrees.com to update your resource key.   But the PHP script on my server is originating from my domain.  The authorized error isn't showing my domain.

Should I not even be defining a domain?

```
use fiftyone\pipeline\devicedetection\DeviceDetectionCloud;
use fiftyone\pipeline\core\PipelineBuilder;
use fiftyone\pipeline\core\Logger;
use fiftyone\pipeline\cloudrequestengine\CloudRequestEngine;

function checkDevice() {
  $cloudRequestEngine = new CloudRequestEngine(array("resourceKey"=>"myResourceKey"));
  $deviceDetection = new DeviceDetectionCloud();  
  
  $Pipeline = (new PipelineBuilder())
              ->add($cloudRequestEngine)
              ->add($deviceDetection)
              ->build();
  $FlowData = $Pipeline->createFlowData();
  
  $FlowData->evidence->set("header.user-agent",$_SERVER['HTTP_USER_AGENT']);  
  // Process the FlowData
  $FlowData->process();
  $devType = checkProperty($FlowData->device->hardwaremodel) ;
  return $devType ;
}
$devType = checkDevice() ;
```

It all seems pretty straight forward, but I can't get either JS client side or PHP server side working correctly with a domain bound resourceKey.  Obviously, I am doing something wrong but can't figure out what.

**UPDATE**:

1)  I created a new resourceKey but did not add a domain to lock it down, and I am no longer getting Authorization errors.  What must I do with the keys that have a domain attached it?  

2) In both the JS and the PHP scripts, the `hardwaremodel` is simply returning `iPhone` - when according to the documentation I was expecting something like `iPhone X`.

3) And `hardwarename` is returning a full array of iPhone names, how do I extract the exact/correct model?

> iPhone,iPhone 11,iPhone 11 Pro,iPhone 11 Pro Max,iPhone 12,iPhone 12 Pro,iPhone 12 Pro Max,iPhone 12 mini,iPhone 3G,iPhone 3GS,iPhone 4,iPhone 4S,iPhone 5,iPhone 5S,iPhone 5c,iPhone 6,iPhone 6 Plus,iPhone 6s,iPhone 6s Plus,iPhone 7,iPhone 7 Plus,iPhone 8,iPhone 8 Plus,iPhone SE,iPhone SE (2nd Gen.),iPhone X,iPhone XR,iPhone XS,iPhone XS Max

**Comment by rolinger** [comment]
I slept on and reread things again this morning.  And now I see why my domain.com resourceKeys are failing - I need to add a proper `referrer` and `origin` to my http headers and permit them on my server `Access-Control-Allow-Headers`.

However, my #2 & #3 above are still an issue.  How can I extract the exact device model when it comes to iPhones or iPads?  Is there another property, besides `hardwaremodel/hardwarename`, I should be querying for that?

**Comment by Steve51D** [comment]
Hi @rolinger,
The origin header to use when making cloud requests can now be more easily specified as described here: https://github.com/51Degrees/pipeline-php-cloudrequestengine/issues/2


iPhone models are trickier than most devices because Apple specifically make the user agent look the same regardless of model.
We get around this by using some additional JavaScript to gather properties on the client side, which are then used to narrow down the exact model. However, this does require a little bit of extra set up.

We have a [web integration example](http://51degrees.com/documentation/_examples__device_detection__web_integration__examples.html) which demonstrates how to do this for most languages.

The pure client-side JavaScript implementation is not covered there though. For that, see the Client-Side Overrides section in the [cloud API documentation](https://cloud.51degrees.com/api-docs/index.html).

**Comment by rolinger** [comment]
@Steve51D - thanks for the response.  I have moved my implementation to use the server-side PHP script only so hopefully your linked `pipeline-php-cloudrequestengine` will do the trick for me.

I just reviewed the `web integration example` and see how its combining both PHP/JS in the single page.  Previously, even though my client page was served by PHP, I was only adding the JS to it.  That page ultimately would send a XMLHttpRequest back to a PHP tracking script that would then try to determine the device model.  

Lastly, whats the difference between `DeviceDetectionCloud` and `DeviceDetectionPipelineBuilder` - which one should I be using?  Do both take an array parameter, ie: `DeviceDetectionCloud(array("cloudRequestOrigin"=>"mydomain.com")) ;`

**Comment by Steve51D** [comment]
@rolinger 
`DeviceDetectionCloud` is a 'cloud engine' in our terminology. This means that it is just converting a response from our cloud service and into a more easily usable form.
In order to make the request to the cloud service, you'll also need a `CloudRequestEngine` in the same pipeline.

The `DeviceDetectionPipelineBuilder` is a quality of life helper. It will create both the `CloudRequestEngine` and the `DeviceDetectionCloud` and add them to the pipeline for you. It's not as flexible as creating all the individual engines yourself, but is sufficient for most use cases.

**Comment by rolinger** [comment]
@Steve51D - ok, thanks for clarification. 

I added the following to my class calls, and am still getting the Authentication errors, but it still works when I use a key that has no domain bound to it, any thoughts? :

```
  $cloudRequestEngine = new CloudRequestEngine(array("resourceKey"=>$key,"cloudRequestOrigin"=>$domains));
  $deviceDetection = new DeviceDetectionCloud(array("resourceKey"=>$key,"cloudRequestOrigin"=>$domains));  
  
  $Pipeline = (new PipelineBuilder())
              ->add($cloudRequestEngine)
              ->add($deviceDetection)
              ->build();
  $FlowData = $Pipeline->createFlowData();
```

**Comment by Steve51D** [comment]
@rolinger 
You can omit the arguments for DeviceDetectionCloud, they're only needed for the request. i.e.:

```
$cloudRequestEngine = new CloudRequestEngine(array("resourceKey"=>$key,"cloudRequestOrigin"=>$domains));
$deviceDetection = new DeviceDetectionCloud();  
```

Otherwise, it looks fine, just a couple of things I can think of:
- Are you using the latest versions of everything that were released a few days ago?
- What is in $domains? If I configure a resource key to work for domains 'abc.com, test.com', then I could set my origin header to 'abc.com' or 'test.com', but sending a comma separated list, or something like that wouldn't work.

**Comment by rolinger** [comment]
@Steve51D - I am using the latest version, I just installed for the first time last night.  Good to know about multiple domains, but that's not the situation here:  `$domains = "mydomain.com" ;`  - a single domain.

I modified my calls and removed the `resourceKey & cloudRequestOrigin` from the `DeviceDetectionCloud` and the domain bound $key is still not working.

If I provide my keys to you, via email, can you check to see if they are setup right?  Or what else can we do from here?

**Comment by Steve51D** [comment]
@rolinger Sure, my email address is in my profile. If you send the keys through, then I'll be able to check them and hopefully figure out what's going wrong.

**Comment by rolinger** [comment]
@Steve51D - thanks again.  I just sent email.  Let me know what you find.

**Comment by Steve51D** [comment]
For future reference, the issue here was a discrepancy between the domain filter configured against the resource key and the value being passed in the origin header.

The domain filter was set to `*.domain.com`
The cloud request origin value was set to `domain.com`

Either the filter needs to be changed to `domain.com` or the cloud request origin to e.g. `abc.domain.com`
