### ISSUE TITLE
Cloud documentation `/api/v4/JS` and `/api/v4/Json` examples do not add resource key to the request

### ISSUE THREAD

**Issue by Joseph51D** [51Degrees/cloud-issues#3]
In the [cloud api-docs](https://cloud.51degrees.com/api-docs/index.html), the examples for the `/api/v4/JS` and the `/api/v4/Json` endpoints do not add the resource key to the request as a parameter.

This results in a 401 response: `curl -X GET "https://cloud.51degrees.com/api/v4/JS" -H "accept: application/javascript"`

The correct URL should include the resource key as a parameter: `https://cloud.51degrees.com/api/v4/js?resource=<resource_key>`

**Comment by Steve51D** [comment]
The problem here is that there are two routes to present the same parameter in different ways. For example:
- `https://cloud-51degrees.com/api/v4/JS?resource=1a2b3c`
- `https://cloud-51degrees.com/api/v4/1a2b3c.JS`

The swagger UI 'understands' that there are two different routes, but cannot seem to associate each route with a separate source for the resource key parameter.
I'm not sure this can be resolved without changing the interface to the API.

**Comment by Steve51D** [comment]
Telemetry shows that the JS endpoint that takes the resource key in the query string is not used.
However, for the JSON endpoint both variations are used in similar quantities.

**Comment by justadreamer** [comment]
Is this issue still relevant? I think you are now passing the resource key as a name of the resource itself: 

```
/api/v4/<your_resource_Key>.json
/api/v4/<your_resource_Key>.js
```
If so probably makes sense to close.

**Comment by Sara51D** [comment]
Closing the issue , see image below, showing resource key 'test' being passed
![Image](https://user-images.githubusercontent.com/97543056/225589396-c0559699-e93a-4eb2-b75f-c0374cc6a23a.png)
